scrolling.init();
sondage.init();
historique.init();
carte.init();
gallerie.run();
timeLine.set('#presentation h2,#t1,#t2,#t3,#t4,#t5', {opacity:'0'});
timeLine.set('#presentation h2', {transform:'translateY(-20px)'});
timeLine.to('#presentation h2', 2, {transform:'translateY(20px)',opacity:'1', ease: Power2.easeInOut});
timeLine.to('#t1', 3, {opacity:'1', ease: Power2.easeInOut});
timeLine.to('#t1', 3, {opacity:'0',display:'none', ease: Power2.easeInOut} );
timeLine.to('#t2', 3, {opacity:'1',display:'block', ease: Power2.easeInOut});
timeLine.to('#t2', 3, {opacity:'0',display:'none', ease: Power2.easeInOut});
timeLine.to('#t3', 3, {opacity:'1',display:'block', ease: Power2.easeInOut});
timeLine.to('#t3', 3, {opacity:'0',display:'none', ease: Power2.easeInOut});
timeLine.to('#t4', 3, {opacity:'1',display:'block', ease: Power2.easeInOut});
timeLine.to('#t4', 3, {opacity:'0',display:'none', ease: Power2.easeInOut});
timeLine.to('#t5', 3, {opacity:'1',display:'block', ease: Power2.easeInOut});
timeLine.to('#t5,#presentation h2' ,10, {opacity:'0',display:'none', ease: Power2.easeInOut});
